# Generated by Django 3.1.3 on 2020-11-23 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('league_type', models.CharField(max_length=50, verbose_name='type')),
                ('logo', models.URLField(verbose_name='logo')),
                ('country_name', models.CharField(max_length=50, verbose_name='country')),
                ('country_code', models.CharField(max_length=5, verbose_name='country_code')),
                ('country_flag', models.URLField(verbose_name='country_flag')),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('firsname', models.CharField(max_length=50, verbose_name='first name')),
                ('lastname', models.CharField(max_length=50, verbose_name='last name')),
                ('age', models.PositiveIntegerField(verbose_name='age')),
                ('birth_country', models.CharField(max_length=50, verbose_name='birth country')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('birth_place', models.CharField(max_length=50, verbose_name='birth place')),
                ('height', models.CharField(max_length=50, verbose_name='height')),
                ('nationality', models.CharField(max_length=50, verbose_name='nationality')),
                ('weight', models.CharField(max_length=50, verbose_name='weight')),
                ('photo', models.URLField(verbose_name='photo')),
                ('injured', models.BooleanField(verbose_name='injured')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_red', models.PositiveIntegerField(verbose_name='red cards')),
                ('cards_yellow', models.PositiveIntegerField(verbose_name='yellow cards')),
                ('crars_yellowred', models.PositiveIntegerField(verbose_name='yellowred cards')),
                ('dribbles_attemps', models.PositiveIntegerField(verbose_name='dribble attemps')),
                ('dribbles_past', models.PositiveIntegerField(verbose_name='dribbles past')),
                ('dibbles_success', models.PositiveIntegerField(verbose_name='successful dribbles')),
                ('duels_total', models.PositiveIntegerField(verbose_name='total duels')),
                ('duels_won', models.PositiveIntegerField(verbose_name='duels won')),
                ('fouls_commited', models.PositiveIntegerField(verbose_name='fouls commited')),
                ('fouls_drawn', models.PositiveIntegerField(verbose_name='fouls drawn')),
                ('games_apperances', models.PositiveIntegerField(verbose_name='apperances')),
                ('games_captin', models.PositiveIntegerField(verbose_name='captin games')),
                ('games_lineups', models.PositiveIntegerField(verbose_name='lineups')),
                ('games_minutes', models.PositiveIntegerField(verbose_name='played minutes')),
                ('games_number', models.PositiveIntegerField(verbose_name='shirt number')),
                ('games_position', models.CharField(max_length=50, verbose_name='position')),
                ('games_rating', models.FloatField(verbose_name='rating')),
                ('goals_assisted', models.PositiveIntegerField(verbose_name='asisted goals')),
                ('goals_scored', models.PositiveIntegerField(verbose_name='goals scored')),
                ('goals_conceded', models.PositiveIntegerField(verbose_name='goals conceded')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player', verbose_name='player')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('start', models.DateField(verbose_name='start')),
                ('end', models.DateField(verbose_name='end')),
                ('current', models.BooleanField(verbose_name='current')),
                ('coverage_fixtures_events', models.BooleanField(verbose_name='Events Coverage')),
                ('coverage_fixtures_lineups', models.BooleanField(verbose_name='fixtures lineups')),
                ('coverage_fixtures_stats', models.BooleanField(verbose_name='fixtures stats')),
                ('coverage_fixtures_player_stats', models.BooleanField(verbose_name='fixture player stats')),
                ('coverage_standings', models.BooleanField(verbose_name='standings coverage')),
                ('coverage_players', models.BooleanField(verbose_name='players coverage')),
                ('coverage_predictions', models.BooleanField(verbose_name='predictions coverage')),
                ('coverage_odds', models.BooleanField(verbose_name='odds coverage')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='api.league', verbose_name='league')),
                ('players', models.ManyToManyField(related_name='seasons', through='api.PlayerStats', to='api.Player', verbose_name='players')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('founded', models.PositiveIntegerField(verbose_name='founded')),
                ('national', models.BooleanField(verbose_name='national')),
                ('logo', models.URLField(verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgst_goals_against_home', models.PositiveIntegerField(verbose_name='biggest home goals conceded')),
                ('bgst_goals_against_away', models.PositiveIntegerField(verbose_name='biggest away goals conceded')),
                ('bgst_goals_for_home', models.PositiveIntegerField(verbose_name='biggest home goals scored')),
                ('bgst_goals_for_away', models.PositiveIntegerField(verbose_name='biggest away goals scored')),
                ('clean_sheet_home', models.PositiveIntegerField(verbose_name='clean sheets home')),
                ('clean_sheet_away', models.PositiveIntegerField(verbose_name='clean sheets away')),
                ('failed_to_score_home', models.PositiveIntegerField(verbose_name='failed to score home')),
                ('failed_to_score_away', models.PositiveIntegerField(verbose_name='failed to score away')),
                ('fixtures_draws_away', models.PositiveIntegerField(verbose_name='draws away')),
                ('fixtures_draws_home', models.PositiveIntegerField(verbose_name='draws home')),
                ('fixture_loses_away', models.PositiveIntegerField(verbose_name='loses away')),
                ('fixture_loses_home', models.PositiveIntegerField(verbose_name='loses home')),
                ('fixture_wins_away', models.PositiveIntegerField(verbose_name='wins away')),
                ('fixture_wins_home', models.PositiveIntegerField(verbose_name='wins home')),
                ('goals_against_average_away', models.PositiveIntegerField(verbose_name='goals against average home')),
                ('goals_against_average_home', models.PositiveIntegerField(verbose_name='goals against average home')),
                ('goals_against_total_away', models.PositiveIntegerField(verbose_name='goals against total home')),
                ('goals_against_total_home', models.PositiveIntegerField(verbose_name='goals against total home')),
                ('goals_for_average_away', models.PositiveIntegerField(verbose_name='goals scored average away')),
                ('goals_for_average_home', models.PositiveIntegerField(verbose_name='goals scored average home')),
                ('goals_for_total_away', models.PositiveIntegerField(verbose_name='goals scored average away')),
                ('goals_for_total_home', models.PositiveIntegerField(verbose_name='goals scored total home')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season', verbose_name='season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team', verbose_name='team')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(related_name='seasons', through='api.TeamStats', to='api.Team', verbose_name='teams'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season', verbose_name='season '),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(related_name='player', to='api.Team', verbose_name='teams'),
        ),
    ]
