# Generated by Django 3.1.3 on 2020-11-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201124_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='coverage_top_scorers',
            field=models.BooleanField(null=True, verbose_name='top scorers coverage'),
        ),
    ]
