# Generated by Django 3.1.3 on 2020-11-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_season_coverage_top_scorers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstats',
            name='bgst_loses_away',
            field=models.CharField(max_length=10, null=True, verbose_name='biggest loses away'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='bgst_loses_home',
            field=models.CharField(max_length=10, null=True, verbose_name='biggest loses home'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='bgst_streak_draws',
            field=models.PositiveIntegerField(null=True, verbose_name='biggest streak draws'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='bgst_streak_loses',
            field=models.PositiveIntegerField(null=True, verbose_name='biggest streak loses'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='bgst_streak_wins',
            field=models.PositiveIntegerField(null=True, verbose_name='biggest streak wins'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='bgst_wins_away',
            field=models.CharField(max_length=10, null=True, verbose_name='biggest wins away'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='bgst_wins_home',
            field=models.CharField(max_length=10, null=True, verbose_name='biggest wins home'),
        ),
    ]
