# Generated by Django 3.1.3 on 2020-11-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201129_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='firsname',
            new_name='firstname',
        ),
    ]
