# Generated by Django 3.1.3 on 2020-12-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201130_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='crars_yellowred',
            new_name='crads_yellowred',
        ),
    ]
