# Generated by Django 3.1.3 on 2020-12-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201201_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='dribbles_attemps',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='dribbles_attempts',
            field=models.PositiveIntegerField(null=True, verbose_name='dribble attempts'),
        ),
    ]
