# Generated by Django 3.1.3 on 2020-12-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201201_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='fouls_commited',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='fouls_committed',
            field=models.PositiveIntegerField(null=True, verbose_name='fouls committed'),
        ),
    ]
