# Generated by Django 3.1.3 on 2020-12-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201201_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='games_apperances',
            new_name='games_apperences',
        ),
    ]
