# Generated by Django 3.1.3 on 2020-12-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201201_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='games_apperences',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='games_appearences',
            field=models.PositiveIntegerField(null=True, verbose_name='appearances'),
        ),
    ]
