# Generated by Django 3.1.3 on 2020-12-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201201_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='games_captin',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='games_captain',
            field=models.PositiveIntegerField(null=True, verbose_name='captain games'),
        ),
    ]
