# Generated by Django 3.1.3 on 2020-12-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201201_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='id',
            new_name='league_id',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='logo',
            new_name='league_logo',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='name',
            new_name='league_name',
        ),
    ]
