# Generated by Django 3.1.3 on 2020-12-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201203_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='coverage_fixtures_stats',
            new_name='coverage_fixtures_statistics',
        ),
    ]
