# Generated by Django 3.1.3 on 2020-12-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201203_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'league', 'verbose_name_plural': 'leagues'},
        ),
    ]
