# Generated by Django 3.1.3 on 2020-12-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201203_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='country',
            new_name='team_country',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='founded',
            new_name='team_founded',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='id',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='logo',
            new_name='team_logo',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='national',
            new_name='team_national',
        ),
    ]
