# Generated by Django 3.1.3 on 2020-12-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201207_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team', verbose_name='team'),
        ),
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together={('player', 'season', 'team')},
        ),
    ]
