# Generated by Django 3.1.3 on 2020-12-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201207_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='cards_red',
            new_name='statistics_cards_red',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='cards_yellow',
            new_name='statistics_cards_yellow',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='crads_yellowred',
            new_name='statistics_crads_yellowred',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='dibbles_success',
            new_name='statistics_dibbles_success',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='dribbles_attempts',
            new_name='statistics_dribbles_attempts',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='dribbles_past',
            new_name='statistics_dribbles_past',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='duels_total',
            new_name='statistics_duels_total',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='duels_won',
            new_name='statistics_duels_won',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='fouls_drawn',
            new_name='statistics_fouls_drawn',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='games_appearences',
            new_name='statistics_games_appearences',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='games_captain',
            new_name='statistics_games_captain',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='games_lineups',
            new_name='statistics_games_lineups',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='games_minutes',
            new_name='statistics_games_minutes',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='games_number',
            new_name='statistics_games_number',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='games_position',
            new_name='statistics_games_position',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='games_rating',
            new_name='statistics_games_rating',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='goals_assisted',
            new_name='statistics_goals_assisted',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='goals_conceded',
            new_name='statistics_goals_conceded',
        ),
        migrations.RenameField(
            model_name='playerstats',
            old_name='goals_scored',
            new_name='statistics_goals_scored',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='fouls_committed',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='statistics_fouls_committed',
            field=models.PositiveIntegerField(null=True, verbose_name='fouls committed'),
        ),
    ]
