# Generated by Django 3.1.3 on 2020-12-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20201207_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='statistics_goals_scored',
            new_name='statistics_goals_total',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='statistics_goals_assisted',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='statistics_goals_assists',
            field=models.PositiveIntegerField(null=True, verbose_name='assists'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='statistics_goals_saves',
            field=models.PositiveIntegerField(null=True, verbose_name='goals saves'),
        ),
    ]
