# Generated by Django 3.1.3 on 2020-12-07 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20201207_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_dribbles_attempts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='dribble attempts'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_fouls_committed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='fouls committed'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_games_appearences',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='appearances'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_games_captain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='captain games'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_goals_assists',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='assists'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_goals_saves',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='goals saves'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='season',
            name='coverage_top_scorers',
            field=models.BooleanField(blank=True, null=True, verbose_name='top scorers coverage'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='biggest_loses_away',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='biggest loses away'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='biggest_loses_home',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='biggest loses home'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='biggest_streak_draws',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='biggest streak draws'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='biggest_streak_loses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='biggest streak loses'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='biggest_streak_wins',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='biggest streak wins'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='biggest_wins_away',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='biggest wins away'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='biggest_wins_home',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='biggest wins home'),
        ),
    ]
