# Generated by Django 3.1.3 on 2020-12-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20201207_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_cards_red',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='red cards'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_cards_yellow',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='yellow cards'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_cards_yellowred',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='yellowred cards'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_dribbles_past',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='dribbles past'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_dribbles_success',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='successful dribbles'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_duels_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='total duels'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_duels_won',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='duels won'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_fouls_drawn',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='fouls drawn'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_games_lineups',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='lineups'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_games_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='played minutes'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_games_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='shirt number'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_games_position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_games_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_goals_conceded',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='goals conceded'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_goals_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='goals scored'),
        ),
    ]
