# Generated by Django 3.1.3 on 2020-12-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20201207_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='statistics_games_captain',
            field=models.BooleanField(blank=True, null=True, verbose_name='captain games'),
        ),
    ]
