# Generated by Django 3.1.3 on 2020-12-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_asyncactionreport_taskresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_birth_country',
            new_name='birth_country',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_birth_date',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_birth_place',
            new_name='birth_place',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_injured',
            new_name='injured',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_nationality',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_weight',
            new_name='weight',
        ),
    ]
