# Generated by Django 3.1.3 on 2020-12-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20201209_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(max_length=50, null=True, verbose_name='weight'),
        ),
    ]
