# Generated by Django 3.1.3 on 2020-12-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20201212_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_country',
            field=models.CharField(max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_founded',
            field=models.PositiveIntegerField(null=True, verbose_name='founded'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_national',
            field=models.BooleanField(null=True, verbose_name='national'),
        ),
    ]
